// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ColegioCRUDApp.Models;

public partial class Alumno
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellidos { get; set; }

    public string Genero { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public virtual ICollection<AlumnoGrado> AlumnoGrado { get; set; } = new List<AlumnoGrado>();
}

public partial class Alumno1
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellidos { get; set; }

    public string Genero { get; set; }

    public DateTime? FechaNacimiento { get; set; }
}