// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ColegioCRUDApp.Models;

public partial class AlumnoGrado
{
    public int Id { get; set; }

    public int? AlumnoId { get; set; }

    public int? GradoId { get; set; }

    public string Seccion { get; set; }

    public virtual Alumno Alumno { get; set; }

    public virtual Grado Grado { get; set; }
}
public partial class AlumnoGrado1
{
    public int Id { get; set; }

    public int? AlumnoId { get; set; }

    public int? GradoId { get; set; }

    public string Seccion { get; set; }

}
