// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ColegioCRUDApp.Models;

public partial class ColegioCRUDContext : DbContext
{
    public ColegioCRUDContext(DbContextOptions<ColegioCRUDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alumno> Alumno { get; set; }

    public virtual DbSet<AlumnoGrado> AlumnoGrado { get; set; }

    public virtual DbSet<Grado> Grado { get; set; }

    public virtual DbSet<Profesor> Profesor { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Alumno>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Alumno__3214EC076AF74705");

            entity.Property(e => e.Apellidos)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FechaNacimiento).HasColumnType("date");
            entity.Property(e => e.Genero)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<AlumnoGrado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AlumnoGr__3214EC078D97CD9F");

            entity.Property(e => e.Seccion)
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Alumno).WithMany(p => p.AlumnoGrado)
                .HasForeignKey(d => d.AlumnoId)
                .HasConstraintName("FK__AlumnoGra__Alumn__3E52440B");

            entity.HasOne(d => d.Grado).WithMany(p => p.AlumnoGrado)
                .HasForeignKey(d => d.GradoId)
                .HasConstraintName("FK__AlumnoGra__Grado__3F466844");
        });

        modelBuilder.Entity<Grado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Grado__3214EC07EE8D0ED8");

            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Profesor).WithMany(p => p.Grado)
                .HasForeignKey(d => d.ProfesorId)
                .HasConstraintName("FK__Grado__ProfesorI__3B75D760");
        });

        modelBuilder.Entity<Profesor>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Profesor__3214EC07F7EEB451");

            entity.Property(e => e.Apellido)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Genero)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Nombre)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}