// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ColegioCRUDApp.Models;

public partial class Grado
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? ProfesorId { get; set; }

    public virtual ICollection<AlumnoGrado> AlumnoGrado { get; set; } = new List<AlumnoGrado>();

    public virtual Profesor Profesor { get; set; }
}

public partial class Grado1
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? ProfesorId { get; set; }
}