// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ColegioCRUDApp.Models;

public partial class Profesor
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Genero { get; set; }

    public virtual ICollection<Grado> Grado { get; set; } = new List<Grado>();
}

public partial class Profesor1
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Genero { get; set; }

}