// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class CtsOu
{
    public int Itemid { get; set; }

    public int? OuId { get; set; }

    public int? CtsRetursId { get; set; }

    public bool? Active { get; set; }

    public DateTime? CtsOuRepair { get; set; }

    public string CtsOuRepairComment { get; set; }

    public string CtsOuRepairEditBy { get; set; }

    public string UserRepairOu { get; set; }
}