// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class CtsReturns
{
    public int Itemid { get; set; }

    public string Vin { get; set; }

    public DateTime? StartCts { get; set; }

    public DateTime? FinishCts { get; set; }

    public string Discrepancy { get; set; }

    public int StatusCts { get; set; }

    public string Customer { get; set; }

    public bool? Active { get; set; }

    public bool? Material { get; set; }

    public DateTime? StartChasisDate { get; set; }

    public DateTime? ReleaseMfgDate { get; set; }

    public string UserRequestedCts { get; set; }

    public DateTime RequestedCts { get; set; }

    public string EtaCommentCts { get; set; }

    public string CommentRepair { get; set; }

    public DateTime? EtaCommentCtsRepair { get; set; }

    public DateTime? EtaFinishCtsQa { get; set; }

    public string ItemAndCode { get; set; }

    public int? FinderBy { get; set; }

    public bool? WasRejectToReleaseByPlant { get; set; }

    public string NoteRejectToReleaseByPlant { get; set; }

    public bool? WasAcceptedToIngressByPlant { get; set; }

    public string NoteRejectToIngressByPlant { get; set; }

    public string UserEdit { get; set; }

    public string UserAcceptIngress { get; set; }

    public string UserAcceptRepair { get; set; }

    public virtual Ou FinderByNavigation { get; set; }
}