// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class LogCtsReturns
{
    public int Itemid { get; set; }

    public string TableLog { get; set; }

    public string UserLog { get; set; }

    public string TextLog { get; set; }

    public DateTime? Date { get; set; }
}