// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class Mails
{
    public int Itemid { get; set; }

    public string Title { get; set; }

    public string Notes { get; set; }

    public string Mails1 { get; set; }

    public bool? Enabled { get; set; }

    public int? OuId { get; set; }
}