// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class Ou
{
    public int Itemid { get; set; }

    public string OuName { get; set; }

    public int? OuNumber { get; set; }

    public bool? Active { get; set; }

    public string MailTo { get; set; }

    public virtual ICollection<CtsReturns> CtsReturns { get; set; } = new List<CtsReturns>();
}