// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class StatusCts
{
    public int Itemid { get; set; }

    public string DescripcionStatus { get; set; }

    public int? IdStatusReferenceSecuence { get; set; }
}