// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CTS_ReturnsApp.Models;

public partial class UnitHistoryCts
{
    public int Itemid { get; set; }

    public string Vin { get; set; }

    public string Notes { get; set; }

    public string UserHistory { get; set; }

    public string OuActual { get; set; }

    public int? PosixTimestamp { get; set; }

    public int? CtsRetursId { get; set; }
}